var _____WB$wombat$assign$function_____ = function(name) {return (self._wb_wombat && self._wb_wombat.local_init && self._wb_wombat.local_init(name)) || self[name]; };
if (!self.__WB_pmw) { self.__WB_pmw = function(obj) { this.__WB_source = obj; return this; } }
{
  let window = _____WB$wombat$assign$function_____("window");
  let self = _____WB$wombat$assign$function_____("self");
  let document = _____WB$wombat$assign$function_____("document");
  let location = _____WB$wombat$assign$function_____("location");
  let top = _____WB$wombat$assign$function_____("top");
  let parent = _____WB$wombat$assign$function_____("parent");
  let frames = _____WB$wombat$assign$function_____("frames");
  let opener = _____WB$wombat$assign$function_____("opener");


(function(){var f=null,k=this,aa=function(a,b,c){a=a.split(".");c=c||k;!(a[0]in c)&&c.execScript&&c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&b!==void 0?c[d]=b:c=c[d]?c[d]:c[d]={}},ca=function(){var a=ba;a.getInstance=function(){return a.Ka||(a.Ka=new a)}},da=function(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length==
"number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if(b=="function"&&typeof a.call=="undefined")return"object";return b},m=function(a){return da(a)=="function"};Math.floor(Math.random()*2147483648).toString(36);
var ea=function(a){return a.call.apply(a.bind,arguments)},ga=function(a,b){var c=b||k;if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var b=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(b,d);return a.apply(c,b)}}else return function(){return a.apply(c,arguments)}},n=function(){n=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ea:ga;return n.apply(f,arguments)},o=function(a,b){var c;aa(a,b,c)},p=function(a,
b,c){a[b]=c},q=function(a,b){function c(){}c.prototype=b.prototype;a.Pa=b.prototype;a.prototype=new c};var r=document,s=window,ha=function(){var a=r,b=f;if((a=a.getElementsByTagName("script"))&&a.length)b=a[a.length-1],b=b.parentNode;return b};var t=function(a){var b=0,a=parseFloat(a);return isNaN(a)||a>1||a<0?b:a},ia=function(){var a="1500",b=1500,a=parseInt(a,10);return isNaN(a)?b:a},v=function(a){var b=!1;if(a=="true")return!0;if(a=="false")return!1;return b},ja=/^([\w-]+\.)*([\w-]{2,})(\:[0-9]+)?$/,w=function(a,b){if(!a)return b;var c=a.match(ja);return c?c[0]:b};var ka=function(){return w("","pagead2.googlesyndication.com")};var qa=function(){var a,b="var i=this.id,s=window.google_iframe_oncopy,H=s&&s.handlers,h=H&&H[i],w=this.contentWindow,d;try{d=w.document}catch(e){}if(h&&d&&(!d.body||!d.body.firstChild)){if(h.call){i+='.call';setTimeout(h,0)}else if(h.match){i+='.nav';w.location.replace(h)}s.log&&s.log.push(i)}";a?b.replace(la,"&amp;").replace(ma,"&lt;").replace(na,"&gt;").replace(oa,"&quot;"):pa.test(b)&&(b.indexOf("&")!=-1&&(b=b.replace(la,"&amp;")),b.indexOf("<")!=-1&&(b=b.replace(ma,"&lt;")),b.indexOf(">")!=-1&&
(b=b.replace(na,"&gt;")),b.indexOf('"')!=-1&&b.replace(oa,"&quot;"))},la=/&/g,ma=/</g,na=/>/g,oa=/\"/g,pa=/[&<>\"]/,ta=function(a){if(a.indexOf("&")!=-1)return"document"in k?ra(a):sa(a);return a},ra=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c=document.createElement("div");return a.replace(ua,function(a,e){var g=b[a];if(g)return g;if(e.charAt(0)=="#"){var h=Number("0"+e.substr(1));isNaN(h)||(g=String.fromCharCode(h))}if(!g)c.innerHTML=a+" ",g=c.firstChild.nodeValue.slice(0,
-1);return b[a]=g})},sa=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if(c.charAt(0)=="#"){var d=Number("0"+c.substr(1));if(!isNaN(d))return String.fromCharCode(d)}return a}})},ua=/&([^;\s<&]+);?/g,xa=function(a){for(var b=va,c=0,b=String(b).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),a=String(a).replace(/^[\s\xa0]+|[\s\xa0]+$/g,"").split("."),d=Math.max(b.length,a.length),e=0;c==0&&
e<d;e++){var g=b[e]||"",h=a[e]||"",l=RegExp("(\\d*)(\\D*)","g"),i=RegExp("(\\d*)(\\D*)","g");do{var j=l.exec(g)||["","",""],u=i.exec(h)||["","",""];if(j[0].length==0&&u[0].length==0)break;var c=j[1].length==0?0:parseInt(j[1],10),U=u[1].length==0?0:parseInt(u[1],10),c=wa(c,U)||wa(j[2].length==0,u[2].length==0)||wa(j[2],u[2])}while(c==0)}return c},wa=function(a,b){if(a<b)return-1;else if(a>b)return 1;return 0};var x=function(a,b){this.width=a;this.height=b};x.prototype.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};x.prototype.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};var y,ya,z,za,Aa,Ba=function(){return k.navigator?k.navigator.userAgent:f},Ca=function(){Aa=za=z=ya=y=!1;var a;if(a=Ba()){var b=k.navigator;y=a.indexOf("Opera")==0;ya=!y&&a.indexOf("MSIE")!=-1;za=(z=!y&&a.indexOf("WebKit")!=-1)&&a.indexOf("Mobile")!=-1;Aa=!y&&!z&&b.product=="Gecko"}};Ca();
var Da=y,A=ya,Ea=Aa,Fa=z,Ga=za,Ia=function(){var a="",b;Da&&k.opera?(a=k.opera.version,a=typeof a=="function"?a():a):(Ea?b=/rv\:([^\);]+)(\)|;)/:A?b=/MSIE\s+([^\);]+)(\)|;)/:Fa&&(b=/WebKit\/(\S+)/),b&&(a=(a=b.exec(Ba()))?a[1]:""));if(A&&(b=Ha(),b>parseFloat(a)))return String(b);return a},Ha=function(){var a=k.document;return a?a.documentMode:void 0},va=Ia(),Ja={},B=function(a){return Ja[a]||(Ja[a]=xa(a)>=0)};!A||B("9");!Ea&&!A||A&&B("9")||Ea&&B("1.9.1");A&&B("9");var Ka=function(a){var b=a.document;if(Fa&&!B("500")&&!Ga){typeof a.innerHeight=="undefined"&&(a=window);var b=a.innerHeight,c=a.document.documentElement.scrollHeight;a==a.top&&c<b&&(b-=15);return new x(a.innerWidth,b)}a=b.compatMode=="CSS1Compat"?b.documentElement:b.body;return new x(a.clientWidth,a.clientHeight)};var La="http://"+ka()+"/pagead/show_ads.js";function C(a){return typeof encodeURIComponent=="function"?encodeURIComponent(a):escape(a)}function Ma(){var a,b,c=Na,d=document.createElement("script");d.type="text/javascript";if(a)d.onload=a;if(b)d.id=b;d.src=c;var e=document.getElementsByTagName("head")[0];e&&window.setTimeout(function(){e.appendChild(d)},0)}function Oa(a,b){a.attachEvent?a.attachEvent("onload",b):a.addEventListener&&a.addEventListener("load",b,!1)}
var Pa=function(){var a=D();if(!("google_onload_fired"in a))a.google_onload_fired=!1,Oa(a,function(){a.google_onload_fired=!0})};function Qa(a){var b=s;b.google_image_requests||(b.google_image_requests=[]);var c=new Image;c.src=a;b.google_image_requests.push(c)}function Ra(){var a="msie";if(a in Sa)return Sa[a];return Sa[a]=navigator.userAgent.toLowerCase().indexOf(a)!=-1}var Sa={};
function Ta(){if(navigator.plugins&&navigator.mimeTypes.length){var a=navigator.plugins["Shockwave Flash"];if(a&&a.description)return a.description.replace(/([a-zA-Z]|\s)+/,"").replace(/(\s)+r/,".")}else if(navigator.userAgent&&navigator.userAgent.indexOf("Windows CE")>=0){for(var a=3,b=1;b;)try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash."+(a+1)),a++}catch(c){b=f}return a.toString()}else if(Ra()&&!window.opera){b=f;try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7")}catch(d){a=0;try{b=
new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a=6,b.AllowScriptAccess="always"}catch(e){if(a==6)return a.toString()}try{b=new ActiveXObject("ShockwaveFlash.ShockwaveFlash")}catch(g){}}if(b)return a=b.GetVariable("$version").split(" ")[1],a.replace(/,/g,".")}return"0"}function Ua(a,b){if(!(Math.random()<1.0E-4)){var c=Math.random();if(c<b)return c=Math.floor(c/b*a.length),a[c]}return""}
var Wa=function(a){a.u_tz=-(new Date).getTimezoneOffset();a.u_his=window.history.length;a.u_java=navigator.javaEnabled();if(window.screen)a.u_h=window.screen.height,a.u_w=window.screen.width,a.u_ah=window.screen.availHeight,a.u_aw=window.screen.availWidth,a.u_cd=window.screen.colorDepth;if(navigator.plugins)a.u_nplug=navigator.plugins.length;if(navigator.mimeTypes)a.u_nmime=navigator.mimeTypes.length},Xa=function(a,b){var c=b||s;if(a&&c.top!=c)c=c.top;try{return c.document&&!c.document.body?new x(-1,
-1):Ka(c||window)}catch(d){return new x(-12245933,-12245933)}},Ya=function(a){var b,c=a.length;if(c==0)return 0;b=b||305419896;for(var d=0;d<c;d++){var e=a.charCodeAt(d);b^=(b<<5)+(b>>2)+e&4294967295}return b>0?b:4294967296+b},Za=function(){var a=window;if(a==a.top)return 0;var b=[];b.push(a.document.URL);a.name&&b.push(a.name);var c=!0,a=Xa(!c,a);b.push(a.width.toString());b.push(a.height.toString());return Ya(b.join(""))},$a=function(a){if(!a)return"";for(var b=[],c=0;a&&c<25;a=a.parentNode,++c)b.push(a.id||
"");return b.join()},ab=function(){var a=E;try{return!!a.document}catch(b){return!1}},cb=function(a){if(!a)return f;a&&a.id&&a.id.indexOf("aswift_")==0&&(a=bb(a));return a||f},db=function(a){if(!a)return"";return(a=cb(a))&&a.src||""},bb=function(a){return a=a.contentWindow.document.getElementsByTagName("iframe")[0]},eb=function(a){if(a&&a.name&&a.name.indexOf("google_ads_iframe_")==0)return a.src||"";return""},fb=function(a,b){if(!a)return f;var c=b.getElementById("google_ads_div_"+a+"_ad_container");
c||(c=b.getElementById("google_ads_div_"+a));return c};var gb=t("0.005"),hb=t("0.01"),ib=t("0.001"),jb=t("0.02"),kb=t("0.02"),lb=ia();var mb=v("false"),nb=v("false"),ob=v("false"),pb=v("false");var qb=function(a,b,c){b=n(b,k,a);a=window.onerror;window.onerror=b;try{c()}catch(d){var c=d.toString(),e="";d.fileName&&(e=d.fileName);var g=-1;if(d.lineNumber)g=d.lineNumber;b=b(c,e,g);if(!b)throw d;}window.onerror=a};o("google_protectAndRun",qb);
var sb=function(a,b,c,d){if(Math.random()<0.01){var e=r,a=["http://",w("","pagead2.googlesyndication.com"),"/pagead/gen_204","?id=jserror","&jscb=",mb?1:0,"&jscd=",nb?1:0,"&context=",C(a),"&msg=",C(b),"&file=",C(c),"&line=",C(d.toString()),"&url=",C(e.URL.substring(0,512)),"&ref=",C(e.referrer.substring(0,512))];a.push(rb());Qa(a.join(""))}return!ob};o("google_handleError",sb);
var rb=function(){var a=["&client=",C(s.google_ad_client),"&format=",C(s.google_ad_format),"&slotname=",C(s.google_ad_slot),"&output=",C(s.google_ad_output),"&ad_type=",C(s.google_ad_type)];return a.join("")};var F=function(a){this.ca=[];this.fa=a||window;this.p=0;this.ba=f},tb=function(a,b){this.fn=a;this.win=b};F.prototype.enqueue=function(a,b){this.p==0&&this.ca.length==0&&(!b||b==window)?(this.p=2,this.va(new tb(a,window))):this.Y(a,b)};F.prototype.Y=function(a,b){this.ca.push(new tb(a,b||this.fa));ub(this)};F.prototype.ra=function(a){this.p=1;if(a)this.ba=this.fa.setTimeout(n(this.da,this),a)};F.prototype.da=function(){if(this.p==1){if(this.ba!=f)this.fa.clearTimeout(this.ba),this.ba=f;this.p=0}ub(this)};
F.prototype.statusz=function(){return!0};p(F.prototype,"nq",F.prototype.enqueue);p(F.prototype,"nqa",F.prototype.Y);p(F.prototype,"al",F.prototype.ra);p(F.prototype,"rl",F.prototype.da);p(F.prototype,"sz",F.prototype.statusz);var ub=function(a){a.fa.setTimeout(n(a.Fa,a),0)};F.prototype.Fa=function(){if(this.p==0&&this.ca.length){var a=this.ca.shift();this.p=2;a.win.setTimeout(n(this.va,this,a),0);ub(this)}};F.prototype.va=function(a){this.p=0;a.fn()};var vb=!!window.google_async_iframe_id,E=vb&&window.parent||window,D=function(){if(vb&&!ab()){for(var a="."+r.domain;a.split(".").length>2&&!ab();)r.domain=a=a.substr(a.indexOf(".")+1),E=window.parent;ab()||(E=window)}return E};function wb(a,b){try{return a.top.document==b}catch(c){}return!1};var xb=function(a,b){this.ua=a;this.$=b;this.Ma=0;this.na=!1;this.Ba=this.Ca=this.ka=this.M=f};xb.prototype.getName=function(){return this.$};
var yb=function(a){a.na=!0},zb=function(a){if(!a.M)a.M=(new Date).getTime()},Ab=function(a){if(!a.ka)a.ka=(new Date).getTime()},Bb=function(a){if(!a.Ca)a.Ca=(new Date).getTime()},Cb=function(a){if(!a.Ba)a.Ba=(new Date).getTime()},Db=function(a){return"google_ads_div_"+a.$},Eb=function(a){return"google_ads_iframe_"+a.$},Fb=function(a){a=a.getAttribute("id");return a.substr(18)};
xb.prototype.toString=function(){return"[gam.AdSlot: pubid="+this.ua+", name="+this.$+", iframeLoaded="+this.na+", tries="+this.Ma+"]"};var Gb={google_ad_channel:"channel",google_ad_host:"host",google_ad_host_channel:"h_ch",google_ad_host_tier_id:"ht_id",google_ad_section:"region",google_ad_type:"ad_type",google_adtest:"adtest",google_allow_expandable_ads:"ea",google_alternate_ad_url:"alternate_ad_url",google_alternate_color:"alt_color",google_bid:"bid",google_city:"gcs",google_color_bg:"color_bg",google_color_border:"color_border",google_color_line:"color_line",google_color_link:"color_link",google_color_text:"color_text",google_color_url:"color_url",
google_contents:"contents",google_country:"gl",google_cpm:"cpm",google_cust_age:"cust_age",google_cust_ch:"cust_ch",google_cust_gender:"cust_gender",google_cust_id:"cust_id",google_cust_interests:"cust_interests",google_cust_job:"cust_job",google_cust_l:"cust_l",google_cust_lh:"cust_lh",google_cust_u_url:"cust_u_url",google_disable_video_autoplay:"disable_video_autoplay",google_ed:"ed",google_encoding:"oe",google_feedback:"feedback_link",google_flash_version:"flash",google_font_face:"f",google_font_size:"fs",
google_hints:"hints",google_kw:"kw",google_kw_type:"kw_type",google_language:"hl",google_page_url:"url",google_region:"gr",google_reuse_colors:"reuse_colors",google_safe:"adsafe",google_tag_info:"gut",google_targeting:"targeting",google_targeting_video_doc_id:"tvdi",google_ui_features:"ui",google_ui_version:"uiv",google_video_doc_id:"video_doc_id",google_video_product_type:"video_product_type"},Hb={google_ad_block:"ad_block",google_ad_client:"client",google_ad_format:"format",google_ad_output:"output",
google_ad_callback:"callback",google_ad_height:"h",google_ad_override:"google_ad_override",google_ad_slot:"slotname",google_ad_width:"w",google_ctr_threshold:"ctr_t",google_image_size:"image_size",google_last_modified_time:"lmt",google_max_num_ads:"num_ads",google_max_radlink_len:"max_radlink_len",google_num_radlinks:"num_radlinks",google_num_radlinks_per_unit:"num_radlinks_per_unit",google_only_ads_with_video:"only_ads_with_video",google_rl_dest_url:"rl_dest_url",google_rl_filtering:"rl_filtering",
google_rl_mode:"rl_mode",google_rt:"rt",google_skip:"skip"},Ib={google_only_pyv_ads:"pyv",google_only_userchoice_ads:"uc",google_with_pyv_ads:"withpyv"};var Kb=function(a){this.S=a;Jb(this)},Lb={google_persistent_state:!0,google_persistent_state_async:!0},Mb={},Nb=function(a){a=a&&Lb[a]?a:vb?"google_persistent_state_async":"google_persistent_state";if(Mb[a])return Mb[a];if(a=="google_persistent_state_async")var b=D(),c={};else c=b=D();var d=b[a];if(typeof d!="object"||typeof d.S!="object")return b[a]=Mb[a]=new Kb(c);return Mb[a]=d},Jb=function(a){G(a,1,!1);G(a,2,!1);G(a,3,f);G(a,4,0);G(a,5,0);G(a,6,0);G(a,7,(new Date).getTime());G(a,8,{});G(a,9,{});
G(a,10,{});G(a,11,[]);G(a,12,0);G(a,14,{})},Ob=function(a){switch(a){case 1:return"google_new_domain_enabled";case 2:return"google_new_domain_checked";case 3:return"google_exp_persistent";case 4:return"google_num_sdo_slots";case 5:return"google_num_0ad_slots";case 6:return"google_num_ad_slots";case 7:return"google_correlator";case 8:return"google_prev_ad_formats_by_region";case 9:return"google_prev_ad_slotnames_by_region";case 10:return"google_num_slots_by_channel";case 11:return"google_viewed_host_channels";
case 12:return"google_num_slot_to_show";case 14:return"gaGlobal"}},Pb=function(a){var b=14,b=Ob(b);return a=a.S[b]},Qb=function(a,b){var c=14;return a.S[Ob(c)]=b},G=function(a,b,c){a=a.S;b=Ob(b);a[b]===void 0&&(a[b]=c)},Rb=function(){var a=Nb();return Pb(a)},Sb=function(a){var b={};return Qb(a,b)};qa();var Tb=function(){var a=window,b="google_unique_id";a[b]?++a[b]:a[b]=1;return a[b]},Ub=function(a){var b="google_unique_id",a=a[b];if(typeof a=="number")return a;return 0};var H=function(a){var b=a;a!="about:blank"&&(b=b.replace(/</g,"%3C").replace(/>/g,"%3E").replace(/"/g,"%22").replace(/'/g,"%27"),a=/^https?:\/\//,a.test(b)||(b="unknown:"+b));return b},Vb=/\+/g,Wb=function(){if(pb)return"https://"+w("","securepubads.g.doubleclick.net");return"http://"+w("","pubads.g.doubleclick.net")},Xb=function(){var a=navigator.userAgent,b=a.indexOf("MSIE ");if(b==-1)return 0;else{var c=a.indexOf(";",b);return parseFloat(a.substring(b+
5,c))}},Yb=function(a){a=a.toLowerCase();a.substring(0,3)!="ca-"&&(a="ca-"+a);return a},Zb=function(a,b){if(wb(a,b))return b.URL;return b.referrer},$b=function(a,b){var c=0,d=[];a&&d.push(a);if(b){var e=$a(b);e&&d.push(e)}d.length>0&&(c=Ya(d.join(":")));return c.toString()},ac=function(){var a=window;if(Ub(a)!=1)return"";if(window.google_enable_osd===!0)return"36815006";a=Ua(["36815005","36815006"],jb);a==""&&(a=Ua(["36813007","36813008"],kb));return a};var bc=function(a){this.f={};this.Ha=a},cc=function(a,b,c,d){if(b&&(c||(c=""),b=="google_gl"?b="google_country":b=="google_region"&&(b="google_section"),b in a.Ha&&((d=typeof d=="undefined"||d)||!a.f[b])))a.f[b]=c},dc=function(a,b){for(var c in b.f){var d=b.b(c);m(d)||a.f[c]||(a.f[c]=d)}};bc.prototype.b=function(a){return this.f[a]};bc.prototype.i=function(){var a=[],b;for(b in this.f)if(!m(this.f[b])){var c=Gb[b]||Hb[b]||Ib[b]||f,d=this.f[b];c&&d&&a.push(c+"="+C(d))}return a.join("&")};
var fc=function(a,b,c,d){a=ec(a,b,c,d);b=[];a[0]&&a[0].length>0&&b.push(a[0].join("&"));a[1]&&a[1].length>0&&b.push("sps="+a[1].join("|"));return b.join("&")},ec=function(a,b,c,d){var e=[],g=[],b=b.f,h;for(h in d)if(!m(h)){var l=d[h];if(l){var i="";b[h]!=f&&(i=C(b[h]));var j=[],u=-1,U=-1,fa;for(fa in a)if(!m(a[fa]))if(++u,c[fa]==f)j.push("");else{var Va=c[fa].f;Va[h]!=f?(j.push(C(C(Va[h]))),U=u):j.push("")}if(U>=0){u=C(i);i=[];i.push(u);for(u=0;u<=U;++u)i.push(j[u]);g.push(l+","+i.join(","))}else i&&
e.push(l+"="+i)}}a=[];a.push(e);a.push(g);return a};var gc=function(){var a=s;return!(!a||!(Math.random()<gb&&a.GA_jstiming&&a.GA_jstiming.load&&a.location.protocol=="http:"))},hc=function(a){this.Ea=(this.A=a&&a.GA_jstiming)&&this.A.load};hc.prototype.tick=function(a,b){this.Ea.tick(a,b)};hc.prototype.report=function(a){var b={};b.e=a;this.A.report(this.Ea,b)};var ic=function(){};q(ic,hc);ic.prototype.tick=function(){};ic.prototype.report=function(){};var I=function(a,b,c,d){c<=4&&(b=b+"_"+c,d?a.tick(b,d+"_"+c):a.tick(b))};var kc=function(){this.f={};jc(this)},jc=function(a){var b=r.URL;a.f=lc(b)},lc=function(a){for(var b={},a=a.split("?"),a=a[a.length-1].split("&"),c=0;c<a.length;c++){var d=a[c].split("=");if(d[0]){var e=d[0].toLowerCase();if(e!="google_domain_reset_url")try{b[e]=d.length>1?window.decodeURIComponent?decodeURIComponent(d[1].replace(Vb," ")):unescape(d[1]):""}catch(g){}}}return b};kc.prototype.b=function(a){return a==f?f:this.f[a]};kc.prototype.setParameter=function(a,b){this.f[a]=b};var J=function(a,b){this.a={};this.h=[];this.n={};this.Ga=a;this.aa=new bc(a);this.T={};this.za=!1;this.k=f;this.A=b||f;this.ya={}},mc={ENABLED:"_enabled_",EXPANDABLE:"_expandable_",WIDTH:"_width_",HEIGHT:"_height_"},nc=function(a,b){var c=b.getName();a.a[c]=b},oc=function(a,b,c){b=new xb(b,c);nc(a,b);return b},pc=function(a,b){var c,d,e={},g=mc;e[g.WIDTH]=a;e[g.HEIGHT]=b;e[g.EXPANDABLE]=!!c;e[g.ENABLED]=d===!1?!1:!0;return e},qc=function(a){var b=[],c;for(c in a.a)if(!m(a.a[c])){var d=a.a[c];d.M||
b.push(d)}return b},rc=function(){var a=K(L);a.za=!0};J.prototype.m=function(){return this.h};
var sc=function(a,b){a.h.push(b)},tc=function(a){var b=[],c;for(c in a.a){var d=a.a[c];m(d)||d.M&&(!d.M||!d.ka)&&b.push(c)}return b},vc=function(a){for(var b in a.a)m(a.a[b])||uc(a,b)},uc=function(a,b){var c=a.a[b];zb(c)},wc=function(a,b){var c=a.a[b];Ab(c)},xc=function(a,b){var c=a.a[b];Bb(c)},M=function(a,b){var c=a.a[b];Cb(c);a.A&&I(a.A,"ga_render",a.h.length,"ga_srt")},yc=function(a){var b=0,c;for(c in a.a)m(a.a[c])||b++;return b};
J.prototype.toString=function(){var a="[AdData:",b=[],c;for(c in this.a)m(this.a[c])||b.push(this.a[c].toString());for(var d in this.n)m(this.n[d])||b.push("["+d+","+this.n[d]+"]");a+=b.join();a+="]";return a};J.prototype.c=function(a){return this.a[a]};J.prototype.O=function(){return this.a};
var zc=function(a){var b={},c;for(c in a.a){var d=a.a[c];if(!m(d))d=d.ua,d!=f&&(b[d]=!0)}var a=[],e;for(e in b)b[e]===!0&&a.push(e);return a},Ac=function(a,b,c){if(!(b==f||b.length==0)){if(c==f||c.length==0)c="";var d=a.n[b];a.n[b]=d==f?c:d+","+c}},Bc=function(a,b,c){cc(a.aa,b,c)},Cc=function(a,b,c,d){if(!(b==f||b.length==0)){var e=a.T[b];e==f&&(a.T[b]=new bc(a.Ga));cc(a.T[b],c,d)}},Dc=function(a){var b=[],c;for(c in a.n)m(a.n[c])||b.push(C(c)+"="+C(a.n[c]));return b.join("&")},Ec=function(a,b,c){if(a.k==
f)a.k={};a.k[b]=c},Fc=function(a,b,c){a.ya[b]=c},Hc=function(a,b,c){if(Gc(a,b,c)!=c.URL)return c.domain;return""},Gc=function(a,b,c){return(a=a.aa.b("google_page_url"))||Zb(b,c)},Ic=function(a,b){for(var c=[],d=0;d<b.length;++d){var e="",g=a.k!=f?a.k[b[d]]:f;g&&(e=g._width_+"x"+g._height_);c.push(e)}return c.join()};var N=function(a,b){this.v=a;this.Z=b?b.Z:[];this.s=b?b.s:[];this.Q=b?b.Q:[];this.qa=b?b.qa:0;this.U=b?b.U:[];this.pa=b?b.pa:!1;this.ja=b?b.ja:"";this.z=b?b.z:"";this.oa=b?b.oa:!1},Jc=function(a,b){var c="google_ad_request_done",d=a.v[c],e=a.Z;a.v[c]=function(a){if(a&&a.length>0){var c=a.length>1?a[1].url:f;e.push([b,ta(a[0].url),c])}d(a)}},Kc=function(a,b){a.s.push(b)},Lc=function(a,b){a.Q.push(b)},Na="http://"+ka()+"/pagead/osd.js",Mc=function(a){if(!a.pa)Pa(),Ma(),a.pa=!0},Nc=function(a,b){if(a.s.length>
0)if(a.oa)for(var c=a.v.document.getElementsByTagName("iframe"),d=0;d<c.length;d++){var e=eb(c[d]);e&&b(c[d],e)}else for(d=0;d<a.s.length;d++)(c=a.v.document.getElementById("google_ads_frame"+a.s[d])||a.v.document.getElementById("aswift_"+(a.s[d]-1)))&&b(c,db(c))},Oc=function(a,b){var c=a.Z;if(c.length>0)for(var d=a.v.document.getElementsByTagName("a"),e=0;e<d.length;e++)for(var g=0;g<c.length;g++)if(d[e].href==c[g][1]){var h=d[e].parentNode;if(c[g][2])for(var l=h,i=0;i<4;i++){if(l.innerHTML.indexOf(c[g][2])>
0){h=l;break}l=l.parentNode}b(h,c[g][0]);c.splice(g,1);break}},Qc=function(a,b){for(var c=0;c<a.Q.length;c++){var d=a.Q[c],e=Pc(d);e&&(e=fb(e,a.v.document))&&b(e,d)}};N.prototype.la=function(a){Oc(this,a);Qc(this,a);Nc(this,a)};N.prototype.setupOsd=function(a,b,c){this.qa=a;this.ja=b;this.z=c};N.prototype.getOsdMode=function(){return this.qa};N.prototype.getEid=function(){return this.ja};N.prototype.getCorrelator=function(){return this.z};
N.prototype.ma=function(){return this.Z.length+this.s.length+this.Q.length};N.prototype.setValidOutputTypes=function(a){this.U=a};N.prototype.registerAdBlockByType=function(a,b,c,d){if(this.U.length>0){for(var e=0;e<this.U.length;e++)if(this.U[e]==a)this.oa=c,a=="js"?Jc(this,b):a=="html"?Kc(this,d):a=="json_html"&&Lc(this,b);Mc(this)}};
var Pc=function(a){if((a=a.match(/[&\?](?:slotname)=([^&]+)/))&&a.length==2)return a[1];return""},Rc=function(){var a=D(),b=a.__google_ad_urls;if(!b)return a.__google_ad_urls=new N(a);try{b.getEid()}catch(c){return a.__google_ad_urls=new N(a,b)}return b};o("Goog_AdSense_getAdAdapterInstance",Rc);o("Goog_AdSense_OsdAdapter",N);o("Goog_AdSense_OsdAdapter.prototype.numBlocks",N.prototype.ma);o("Goog_AdSense_OsdAdapter.prototype.findBlocks",N.prototype.la);
o("Goog_AdSense_OsdAdapter.prototype.getOsdMode",N.prototype.getOsdMode);o("Goog_AdSense_OsdAdapter.prototype.getEid",N.prototype.getEid);o("Goog_AdSense_OsdAdapter.prototype.getCorrelator",N.prototype.getCorrelator);o("Goog_AdSense_OsdAdapter.prototype.setValidOutputTypes",N.prototype.setValidOutputTypes);o("Goog_AdSense_OsdAdapter.prototype.setupOsd",N.prototype.setupOsd);o("Goog_AdSense_OsdAdapter.prototype.registerAdBlockByType",N.prototype.registerAdBlockByType);var O=navigator;
function Sc(a,b,c,d,e){var g=Math.round((new Date).getTime()/1E3),h=window.google_analytics_domain_name,a=typeof h=="undefined"?Tc("auto",a):Tc(h,a),l=b.indexOf("__utma="+a+".")>-1,h=b.indexOf("__utmb="+a)>-1,i=b.indexOf("__utmc="+a)>-1,j=Nb("google_persistent_state"),j=Pb(j)||Sb(j);if(l){b=b.split("__utma="+a+".")[1].split(";")[0].split(".");if(h&&i)j.sid=b[3]+"";else if(!j.sid)j.sid=g+"";j.vid=b[0]+"."+b[1];j.from_cookie=!0}else{if(!j.sid)j.sid=g+"";if(!j.vid)j.vid=(Math.round(Math.random()*2147483647)^
Uc(b,c,d,e)&2147483647)+"."+g;j.from_cookie=!1}j.dh=a;if(!j.hid)j.hid=Math.round(Math.random()*2147483647)}function Uc(a,b,c,d){var e=[O.appName,O.version,O.language?O.language:O.browserLanguage,O.platform,O.userAgent,O.javaEnabled()?1:0].join("");c?e+=c.width+"x"+c.height+c.colorDepth:window.java&&(c=java.awt.Toolkit.getDefaultToolkit().getScreenSize(),e+=c.screen.width+"x"+c.screen.height);e+=a;e+=d||"";for(a=e.length;b>0;)e+=b--^a++;return Vc(e)}
function Vc(a){var b=1,c=0,d;if(!(a==void 0||a=="")){b=0;for(d=a.length-1;d>=0;d--)c=a.charCodeAt(d),b=(b<<6&268435455)+c+(c<<14),c=b&266338304,b=c!=0?b^c>>21:b}return b}function Tc(a,b){if(!a||a=="none")return 1;a=String(a);"auto"==a&&(a=b,"www."==a.substring(0,4)&&(a=a.substring(4,a.length)));return Vc(a.toLowerCase())};var Wc=function(a,b,c,d){this._value_=a;this._expires_=b;this._path_=c;this._domain_=d;if(!this._path_)this._path_="/";if(this._domain_==f)this._domain_=document.domain};Wc.prototype.toString=function(){return"[GA_GoogleCookieInfo: value="+this._value_+", expires="+this._expires_+", path="+this._path_+"]"};var P=function(){this.J=Xc(this);this.ia=!1;if(!this.J)this.ia=Yc(this)};P.prototype.ga="__gads=";P.prototype.V="GoogleAdServingTest=";P.prototype.ea=function(a){this.w=a._cookies_[0];if(this.w!=f)this.J=this.w._value_,Zc(this)};
var $c=function(a){var b=(new Date).valueOf(),c=new Date;c.setTime(b+a);return c},ad=function(){var a=15552E6,b=$c(a),a="ID=12345:T="+a,c="/",d=document.domain;return new Wc(a,b.valueOf(),c,d)},bd="http://"+w("","partner.googleadservices.com")+"/gampad/cookie.js?callback=_GA_googleCookieHelper.setCookieInfo",dd=function(){var a=cd(L),b=window.GS_googleGetIdsForAdSenseService();if(!a.J&&a.ia){var a="script",c=document.domain,b=bd+"&client="+C(b)+"&domain="+C(c),b=H(b);document.write("<"+
a+' src="'+b+'"></'+a+">")}},Yc=function(a){document.cookie=a.V+"Good";var b=ed(a.V);if(b=b=="Good"){var c=$c(-1);document.cookie=a.V+"; expires="+c.toGMTString()}return b},Xc=function(a){return a=ed(a.ga)},ed=function(a){var b=document.cookie,c=b.indexOf(a),d="";if(c!=-1){a=c+a.length;c=b.indexOf(";",a);if(c==-1)c=b.length;d=b.substring(a,c)}return d},Zc=function(a){if(a.w!=f&&a.J){var b=new Date;b.setTime(1E3*a.w._expires_);var c=a.w._domain_,a=a.ga+a.J+"; expires="+b.toGMTString()+"; path="+a.w._path_+
"; domain=."+c;document.cookie=a}};p(P.prototype,"setCookieInfo",P.prototype.ea);var Q=function(a,b,c,d){this.adData=b;this.env=c;this.adContentsBySlot=f;this.adUrl="";this.X=d;this.z=0;fd(this);this.d=a;this.ha="";this.Na=Gb;this.u=[];this.sa=[]},gd={WIDTH:"_width_",HEIGHT:"_height_",HTML:"_html_",SNIPPET:"_snippet_",EXPANDABLE:"_expandable_",IS_AFC:"_is_afc_",IS_3PAS:"_is_3pas_",COOKIES:"_cookies_",CREATIVE_IDS:"_cids_",ADGROUP2_IDS:"_a2ids_",PREVIOUSLY_SHOWN_TOKEN:"_pstok_",EMPTY:"_empty_"};Q.prototype.P=function(){return"json_html"};Q.prototype.g=function(){return"lean"};
Q.prototype.getCorrelator=function(){return this.z.toString()};var fd=function(a){var b=(new Date).getTime();a.z=Math.floor(b)};Q.prototype.initialize=function(){hd(this);this.adUrl=this.ha;this.sa=[];this.u=[]};var hd=function(a){a.ha=Wb()+"/gampad/ads?"},id=function(a){a.adUrl=a.ha;R(a,"correlator",a.getCorrelator());S(a,"output",a.P());S(a,"callback",a.F());S(a,"impl",a.H());a.d||a.W()},T=function(a,b){return a.adContentsBySlot!=f?a.adContentsBySlot[b]:f};Q.prototype.c=function(a){return this.adData.c(a)};
Q.prototype.m=function(){return this.adData.m()};Q.prototype.O=function(){return this.adData.O()};
var R=function(a,b,c){c!=f&&S(a,b,C(c.toString()))},S=function(a,b,c){c!=f&&c!=""&&(a.adUrl+=a.adUrl.charAt(a.adUrl.length-1)!="?"?"&"+b+"="+c:b+"="+c)},jd=function(a,b){for(var c=0;c<b.length;c++)if(b[c]!=""){for(var d=!1,e=0;e<a.u.length;e++)if(b[c]==a.u[e]){d=!0;break}d||a.u.push(b[c])}},kd=function(a,b){for(var c="",d=0;d<b.length;d++){if(d>0)c+="/";else if(b[0]=="")continue;for(var e=0;e<a.u.length;e++)if(b[d]==a.u[e]){c+=e;break}}return c},ld=function(a,b){var c="";b!=""&&(c=b.split("/"),jd(a,
c),c=kd(a,c));a.sa.push(c)};Q.prototype.C=function(a){S(this,"gdfp_req",1);var b=[];if(this.d)for(var c=qc(this.adData),d=c.length,e=0;e<d;e++)b.push(c[e].getName());else R(this,"iu",a||""),b=this.adData.m();if(b.length>0){if(a)ld(this,a);else for(e=0;e<d;e++)ld(this,b[e]);R(this,"iu_parts",this.u.join());R(this,"enc_prev_ius",this.sa.join());R(this,"prev_iu_szs",Ic(this.adData,b))}};
var md=function(a,b){if(b==f)return a;var c=a.lastIndexOf("?"),c=a.indexOf("google_preview=",c),d=a.indexOf("&",c);d==-1&&(d=a.length-1,c-=1);return a.substring(0,c)+a.substring(d+1,a.length)};
Q.prototype.B=function(a,b,c){R(this,"url",md(Gc(this.adData,window,document),this.env.b("google_preview")));R(this,"ref",document.referrer);R(this,"lmt",(Date.parse(document.lastModified)/1E3).toString());S(this,"dt",a.getTime());if(document.body){var a=document.body.scrollHeight,d=document.body.clientHeight;d&&a&&R(this,"cc",Math.round(d*100/a).toString())}a=this.env.b("deb");a!=f&&R(this,"deb",a);a=this.env.b("haonly");a!=f&&R(this,"haonly",a);b=this.adData.T[b];a=this.adData.aa;d="";c?d=fc(this.adData.O(),
a,this.adData.T,this.Na):(b==f?b=a:dc(b,a),d=b.i());d&&(this.adUrl+="&"+d)};var nd=function(a){var b=window,c=document;R(a,"cust_params",Dc(a.adData));a.X&&(R(a,"cookie",a.X.J),a.X.ia&&R(a,"cookie_enabled","1"));(b=Hc(a.adData,b,c))&&R(a,"cdm",b)},od=function(a,b){for(var c in b){var d=b[c];m(d)||S(a,c,d)}};Q.prototype.G=function(){return[]};var pd=function(a){try{R(a,"eid",a.G().join())}catch(b){}};
Q.prototype.i=function(a){id(this);this.D(a);if(this.adUrl.length>2E3)a=this.adUrl.lastIndexOf("&",1992),a!=-1?this.adUrl=this.adUrl.substring(0,a):(this.adUrl=this.adUrl.substring(0,1992),this.adUrl=this.adUrl.replace(/%\w?$/,"")),this.adUrl+="&trunc=1";return this.adUrl};
Q.prototype.D=function(a){pd(this);var b=new Date;this.C(a);nd(this);this.env.b("google_preview")!=f&&R(this,"gct",this.env.b("google_preview"));this.B(b,a||f,this.d);a={};Wa(a);od(this,a);S(this,"flash",Ta());S(this,"gads","v2");return this.adUrl};Q.prototype.W=function(){var a=0,b="",c;for(c in this.adContentsBySlot)if(!m(this.adContentsBySlot[c])){var d=this.adContentsBySlot[c],e=d._is_afc_,a=2*a+(e?1:0);d._pstok_&&(b=d._pstok_)}a>0&&S(this,"prev_afc",a);b&&R(this,"pstok",b)};
var qd=function(a,b,c,d,e,g,h){var l="relative",a=a.createElement(b);a.style.width=d+"px";a.style.height=e+"px";a.style.display=g;a.style.position=l;if(h)a.style.margin=h;a.style.border=0;c&&a.appendChild(c);return a},rd=function(a,b,c,d,e,g){e=qd(a,"ins",e,c,d,"block");e=qd(a,"ins",e,c,d,"inline-table");b=a.getElementById(b);g?(a=qd(a,"div",e,c,d,"block","auto"),b.appendChild(a)):b.appendChild(e)},sd=function(a,b,c,d){var e=document,g=T(a,c),h=g._width_,l=g._height_,g=g._html_,i=e.createElement("iframe"),
j=a.adData.c(c),j=Eb(j);i.id=j;i.name=j;i.width=h;i.height=l;i.vspace=0;i.hspace=0;i.allowTransparency="true";i.scrolling="no";i.marginWidth=0;i.marginHeight=0;i.frameBorder=0;i.style.border=0;i.style.position="absolute";i.style.top=0;i.style.left=0;rd(e,b,h,l,i,d);i.contentWindow.document.write(g);i.contentWindow.document.write("<script>document.close();<\/script>");M(a.adData,c)};
Q.prototype.q=function(a,b,c){a=this.env.b("google_collapse_empty_div");if(a=="true"&&(c=this.adData.c(c)))if(b=b.getElementById(Db(c)))b.style.display="none"};Q.prototype.o=function(a){if(this.adContentsBySlot==f){this.adContentsBySlot=a;for(var b in a)m(a[b])||wc(this.adData,b)}else for(b in a)m(a[b])||(this.adContentsBySlot[b]=a[b],wc(this.adData,b));var c=!1;for(b in a)if(!m(a[b])){var d=a[b];if(c)d._cookies_=[ad()],c=!1;d!=f&&d._cookies_!=f&&this.X.ea(d)}};var td=function(a,b){var c=Wb();if(!b||b<0||b>1)b=0;this.La=Math.random()<b;this.Ia=a;this.xa=c+"/pagead/gen_204?id="+C(a);this.Ja=[]},V=function(a,b,c){b&&b.match(/^\w+$/)&&c&&(a.xa+="&"+b+"="+C(c))},ud=function(a,b){var c=zc(b);c.length>0&&V(a,"pub_id",c[0]);V(a,"nslots",yc(b).toString());V(a,"pub_url",document.URL);V(a,"pub_ref",document.referrer)},vd=function(a){if(a.La&&a.Ia&&a.xa){var b=new Image;b.src=a.xa;a.Ja.push(b)}};var W=function(a,b,c,d,e){Q.call(this,a,b,c,d);this.csi=e;this.noRender=this.noFetch=!1;this.R=this.I=f;this.Aa=this.Oa=!1};q(W,Q);W.prototype.g=function(){return"unknown"};W.prototype.initialize=function(){Q.prototype.initialize.call(this);this.noFetch=this.env.b("google_nofetch")!=f||window.google_noFetch;this.noRender=this.env.b("google_norender")!=f;var a=n(this.j,this);wd(a)};W.prototype.G=function(){var a=Q.prototype.G.call(this),b=xd(this);b&&a.push(b);return a};
var wd=function(a){var b=window;b.attachEvent?b.attachEvent("onload",a):b.addEventListener&&b.addEventListener("load",a,!1)},yd=function(a){a.csi.tick("onload");a.csi.report(a.g())},zd=function(a){var b=tc(a.adData);if(b.length>0)a.I=new td("missing_cb",hb),V(a.I,"pending",b.join()),V(a.I,"correlator",a.getCorrelator().toString()),V(a.I,"impl",a.g()),ud(a.I,a.adData),vd(a.I)};W.prototype.j=function(){yd(this);zd(this)};W.prototype.C=function(a){this.Oa?Q.prototype.C.call(this,a):Ad(this,a)};
var Ad=function(a,b){for(var c=qc(a.adData),d=[],e=[],g=[],h=c.length,l=0;l<h;l++){var i=c[l],j=i.getName();g.push(j);b&&b!=j||(d.push(j),e.push(Yb(i.ua)))}R(a,"client",e[0]);a.d?g.length>0&&R(a,"page_slots",g.join()):(R(a,"slotname",d.join()),a.adData.h.length>0&&R(a,"page_slots",a.adData.m().join()))};
W.prototype.B=function(a,b,c){if(navigator.userAgent.indexOf("MSIE ")>0){var d=this.adData.aa;cc(d,"google_encoding",document.charset,!1)}Q.prototype.B.call(this,a,b,c);a=!0;if(a=Xa(a))R(this,"biw",a.width),R(this,"bih",a.height);R(this,"ifi",Ub(window));a=Za();a!=0&&R(this,"ifk",a.toString());b=$b(b,this.adData.ya[b]);R(this,"adk",b)};
var Bd=function(a){var b=window;Sc(b.document.domain,b.document.cookie,b.history.length,b.screen,b.document.referrer);var c=Rb();S(a,"ga_vid",c.vid);S(a,"ga_sid",c.sid);S(a,"ga_hid",c.hid);S(a,"ga_fc",c.from_cookie);R(a,"ga_wpids",b.google_analytics_uacct)};W.prototype.D=function(a){var b=Tb();Q.prototype.D.call(this,a);Bd(this);this.Aa&&Rc().registerAdBlockByType(this.P(),this.adUrl,!0,b);return this.adUrl};
var Cd=function(a){if(a.d){var b=yc(a.adData),c=a.adData.h.length;if(b!=c)a.R=new td("sra_mismatch",ib),V(a.R,"correlator",a.getCorrelator()),V(a.R,"fslots",c.toString()),ud(a.R,a.adData),vd(a.R)}},Dd=function(a,b,c){c='<ins style="position:relative;width:'+a+"px;height:"+b+'px;border:none;display:block;">'+c+"</ins>";return a='<ins style="position:relative;width:'+a+"px;height:"+b+'px;border:none;display:inline-table;">'+c+"</ins>"},Ed=function(a,b,c,d,e,g){var h=!0,l=a.adData.c(b),i=Eb(l),j='"border:0px;left:0;position:absolute;top:0;"',
b=[],c=H(c);b.push("<iframe id=",i," name=",i,' width="',e,'" height="',g,'" vspace="0" hspace="0" allowtransparency="true" ',"scrolling=",a.capture?'"auto"':'"no"',' marginwidth="0" marginheight="0" frameborder="0" style=',j,' src="',c,'"');d!=f&&b.push(' onload="',d,'"');b.push("></iframe>");a=[];h&&(d=Db(l),a.push("<div id=",d,">"));a.push(Dd(e,g,b.join("")));h&&a.push("</div>");e=a.join("");document.write(e)},Fd=function(){var a=[],b=document.getElementsByTagName("base");if(b)for(var c=0,d=b.length;c<
d;++c){var e=b[c],g=e.getAttribute("target");g&&(a.push({baseElement:e,originalTagValue:g}),e.removeAttribute("target"))}return a},Gd=function(a){if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b];d.baseElement.setAttribute("target",d.originalTagValue)}};W.prototype.q=function(a,b,c){a.google_js_backfill?(a="script",b.write("<"+a+' src="'+La+'"></'+a+">")):Q.prototype.q.call(this,a,b,c)};
var Hd=function(a){var b="http://"+ka()+"/pagead/inject_object_div.js";if(parseInt(Xb(),10)>6)return!1;if(a.indexOf(b)<0)return!1;return!0},Id=function(a,b){var c=Fd();window.frames[a.name].contents=b;a.src=Hd(b)?'javascript:document.write(window["contents"]);document.close();':'javascript:window["contents"]';Gd(c)},Jd=function(a,b){var c=Fb(a);try{var d=a.contentWindow?a.contentWindow.document:a.contentDocument;if(d==f)if(document.implementation&&document.implementation.createDocument)d=document.implementation.createDocument("",
c,f);else if(typeof ActiveXObject!="undefined")d=new ActiveXObject("Msxml.DOMDocument");else return;d.open("text/html","replace");d.write(b);d.close()}catch(e){}};W.prototype.o=function(a){I(this.csi,"ga_srt",this.adData.h.length,"_ga_start");Q.prototype.o.call(this,a)};
var xd=function(a){var b=Rc(),c=b.getEid();if(c==""){if(c=ac()){var d=b.getOsdMode();if(c=="36815006"||c=="36813008")b.setValidOutputTypes(["html","json_html"]),d=c=="36815006"?1:0;b.setupOsd(d,c,a.getCorrelator());a.Aa=!0}}else c!="36815006"&&c!="36815005"&&c!="36813008"&&c!="36813007"&&(c="");return c};var X=function(a,b,c,d,e){W.call(this,a,b,c,d,e);this.t=[];this.Da={};this.wa=!1};q(X,W);X.prototype.g=function(){return this.d?"batched_friendly_iframe":"friendly_iframe"};X.prototype.F=function(){return"window.parent.GA_googleSetAdContentsBySlotForAsync"};X.prototype.H=function(){return this.d?"fifs":"fif"};X.prototype.K=function(a){this.i();var b=H(this.adUrl);vc(this.adData);b='<script src = "'+b+'"><\/script>';I(this.csi,"_ga_start",this.adData.h.length);Kd(this,document,a,!0,0,0,b)};
var Ld=function(a,b){sc(a.adData,b);a.i(b);if(a.wa)a.wa=!1,S(a,"fif_to",1);var c=H(a.adUrl);uc(a.adData,b);c='<script src = "'+c+'"><\/script>';I(a.csi,"_ga_start",a.adData.h.length);Kd(a,document,b,!0,0,0,c);a.Da[b]=setTimeout(n(a.ta,a,!0),lb)},Kd=function(a,b,c,d,e,g,h){var c=a.adData.c(c),l=Eb(c);d&&(l+="__hidden__");a=b.getElementById(l);if(!a){a=b.createElement("iframe");a.id=l;a.name=l;if(e!=f&&g!=f)a.width=e,a.height=g;a.vspace=0;a.hspace=0;a.allowTransparency="true";a.scrolling="no";a.marginWidth=
0;a.marginHeight=0;a.frameBorder=0;a.style.border=0;if(d)a.style.visibility="hidden",a.style.display="none";d=Db(c);b=b.getElementById(d);if(b==f)return;b.appendChild(a)}h&&(b=a.contentWindow?a.contentWindow.document:a.contentDocument,b.write(h),b.close())};X.prototype.L=function(a){var b=this.adData.c(a);b!=f&&!this.noFetch&&(Md(this,a),this.t.push(a),this.t.length==1&&Ld(this,a))};
var Md=function(a,b){var c=document,d=a.adData.k!=f?a.adData.k[b]:f,e=d._width_,d=d._height_;Kd(a,c,b,!1,e,d)},Nd=function(a,b){a.o(b);if(a.d)for(var c=a.adData.m(),d=0;d<c.length;d++){var e=c[d];a.l(e)}else{c={};for(e in b)m(b[e])||(c[e]=!0,a.l(e));e=a.t[0];e in c&&(clearTimeout(a.Da[e]),a.ta())}};X.prototype.ta=function(a){if(a)this.wa=!0;this.t.length>0&&(this.t.shift(),this.t.length>0&&Ld(this,this.t[0]))};var Od=function(a,b){var c=a.adData.c(b);c!=f&&(sc(a.adData,b),Md(a,b),c=T(a,b),c!=f&&a.l(b))};
X.prototype.r=function(a){this.d?(Od(this,a),this.adData.h.length==1&&this.K(a)):this.L(a)};X.prototype.l=function(a){try{this.N(window,document,a)}catch(b){}};X.prototype.N=function(a,b,c){var d=this.adData.c(c);if(d!=f){var e=T(this,c);xc(this.adData,c);if(e==f||e._empty_)this.q(a,b,c);else if(!this.noRender){a=Eb(d);b=b.getElementById(a);a=e._html_;d=b.parentNode;if(a==f){d.removeChild(b);return}navigator.userAgent.indexOf("MSIE ")>0?Pd(b,a,e._is_3pas_):Qd(b,a)}M(this.adData,c)}};
var Qd=function(a,b){a.contentWindow.document.write(b);a.contentWindow.document.close()},Pd=function(a,b,c){c?Id(a,b):Jd(a,b)};X.prototype.j=function(){W.prototype.j.call(this);Cd(this)};var Y=function(a,b,c,d,e){W.call(this,a,b,c,d,e)};q(Y,W);Y.prototype.g=function(){return"iframe"};Y.prototype.P=function(){return"html"};Y.prototype.F=function(){return""};Y.prototype.H=function(){return"ifr"};Y.prototype.W=function(){};var Rd=function(a,b){var c;a.d?(a.i(),c=a.adUrl+"&currentslot="+C(b)):c=a.i(b);return c};Y.prototype.r=function(a){var b=this.adData.k!=f?this.adData.k[a]:f;if(b!=f&&(sc(this.adData,a),!this.noFetch)){var c=Rd(this,a);Ed(this,a,c,f,b._width_,b._height_)}};var Sd=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^/?#]*)@)?([\\w\\d\\-\\u0100-\\uffff.%]*)(?::([0-9]+))?)?([^?#]+)?(?:\\?([^#]*))?(?:#(.*))?$"),Td=function(a){return a&&decodeURIComponent(a)},Ud=function(a){var b=3;return a.match(Sd)[b]||f};var Z=function(a,b,c,d,e){W.call(this,a,b,c,d,e);this.adsLoadedCallback="GA_googleSyncAdSlotLoaded";this.createDomIframeCallback="GA_googleCreateDomIframe"};q(Z,W);Z.prototype.g=function(){return this.d?"sync_sra":"sync"};Z.prototype.F=function(){return"GA_googleSetAdContentsBySlotForSync"};Z.prototype.H=function(){return this.d?"ss":"s"};
Z.prototype.L=function(a){var b=this.adData.c(a);b!=f&&!this.noFetch&&(this.i(b.getName()),b=H(this.adUrl),uc(this.adData,a),document.write('<script src = "'+b+'"><\/script>'))};var Vd=function(a,b){a.o(b);if(a.d){var c=a.adData.m();if(c.length==1){c=c[0];a.l(c);return}}for(var d in b)m(b[d])||a.l(d)};Z.prototype.K=function(){this.i();var a=H(this.adUrl);document.write('<script src = "'+a+'"><\/script>');vc(this.adData)};
Z.prototype.r=function(a){sc(this.adData,a);var b=this.adData.h.length;I(this.csi,"_ga_start",b);this.d?b==1?this.K():this.l(a):this.L(a)};Z.prototype.l=function(a){this.N(window,document,a)};
Z.prototype.N=function(a,b,c){var d=this.adData.c(c);if(d!=f)if(d=T(this,c),xc(this.adData,c),d==f||d._empty_)this.q(a,b,c),M(this.adData,c);else if(this.noRender)M(this.adData,c);else if(d._snippet_&&!d._is_afc_)Wd(this,c,b);else if(a.navigator.userAgent.indexOf("MSIE ")>0){var b=this.adsLoadedCallback+"(this);",a="about:blank",e=this.env.b("google_domain_reset_url");if(e){var g=Td(Ud(e));if(g===f||g.indexOf(document.domain)>=0)a=e}Ed(this,c,a,b,d._width_,d._height_)}else d=Xd(this,c,document),b.write("<script>"+
this.createDomIframeCallback+'("'+d+'" ,"'+c+'");<\/script>')};
var Yd=function(a){var b=gd;return a[b.EXPANDABLE]&&!(a[b.IS_AFC]&&a[b.IS_3PAS])},Zd=function(a,b){var c=Fb(b),d=a.adData.c(c);if(!d.na){yb(d);var d=T(a,c),e=b.parentNode,g=d&&d._html_;g?Yd(d)?e.innerHTML=g:d._is_3pas_?Id(b,g):Jd(b,g):e.removeChild(b);M(a.adData,c)}},$d=function(a,b){Fb(b);Zd(a,b)},Xd=function(a,b,c,d){a=a.adData.c(b);a=Db(a)+"_ad_container";b="<div id="+a+">";d&&(b+=d._html_);b+="\n</div>\n";c.write(b);return a},Wd=function(a,b,c){var d=T(a,b);d!=f&&(Xd(a,b,c,d),M(a.adData,b))};
Z.prototype.j=function(){W.prototype.j.call(this);Cd(this)};var ae=function(a,b,c,d,e){var g=f;e!=f?g=e:(g=b.b("google_ad_impl"),g==f&&(g="sync"));switch(g){case "sync":return new Z(!1,a,b,c,d);case "sync_sra":return new Z(!0,a,b,c,d);case "iframe":return new Y(!1,a,b,c,d);case "friendly_iframe":return new X(!1,a,b,c,d);case "batched_friendly_iframe":return new X(!0,a,b,c,d);default:return new Z(!1,a,b,c,d)}};var ba=function(){this.csi=this.settings=this.cookieHelper=this.adEngine=this.adData=f},K=function(a){if(!a.adData)a.adData=new J(Gb);return a.adData},be=function(){var a=L,b=new J(Gb);a.adData=b},$=function(a){var b=L;if(b.adEngine==f)b.adEngine=ae(K(b),ce(b),cd(b),de(b),a),b.adEngine.initialize();return b.adEngine},ee=function(){var a=L,b=f;a.adEngine=b},ce=function(a){window.GA_googleEnv==f&&(window.GA_googleEnv=new kc);if(a.settings==f)a.settings=window.GA_googleEnv;return a.settings},cd=function(a){window._GA_googleCookieHelper==
f&&(window._GA_googleCookieHelper=new P);if(a.cookieHelper==f)a.cookieHelper=window._GA_googleCookieHelper;return a.cookieHelper},de=function(a){if(a.csi==f)a.csi=gc()?new hc(s):new ic;return a.csi};ca();var L=ba.getInstance();function fe(a,b){if(typeof a!="string"||a.length==0)return f;else if(typeof b!="string"||b.length==0)return f;var c=K(L);return oc(c,a,b)}o("GA_googleAddSlot",fe);function ge(){rc();$()}o("GA_googleFetchAds",ge);function he(){$("iframe");dd()}o("GA_googleUseIframeRendering",he);function ie(){$("friendly_iframe")}o("GA_googleUseFriendlyIframeRendering",ie);function je(){$("batched_friendly_iframe")}o("GA_googleUseFriendlyIframeSRARendering",je);
function ke(){var a=ce(L);a.b("google_ad_impl")||a.setParameter("google_ad_impl","sync_sra")}o("GA_googleUseSyncSRARendering",ke);function le(a){var b=ce(L);b.setParameter("google_domain_reset_url",a)}o("GA_googleDomainResetUrl",le);function me(a){var b=$(),c=K(L),d=ha();Fc(c,a,d);c.za&&(c=b.g(),c=="iframe"||c=="friendly_iframe"||c=="batched_friendly_iframe"||(T(b,a)==f||b.d)&&b.r(a))}o("GA_googleFillSlot",me);
function ne(a,b,c,d){var a=a||"",b=b||"",c=c||0,d=d||0,e=$(),g=K(L),h=ha();Fc(g,b,h);h=e.g();h!="iframe"&&h!="friendly_iframe"&&h!="batched_friendly_iframe"||(oc(g,a,b),a=pc(c,d),Ec(g,b,a),e.r(b))}o("GA_googleFillSlotWithSize",ne);function oe(){be();ee()}o("GA_googleResetAll",oe);window.google_noFetch=!1;function pe(){window.google_noFetch=!0}o("GA_googleNoFetch",pe);function qe(){window.google_delayFetch=!0}o("GA_googleDelayFetch",qe);function re(a,b){Ac(K(L),a,b)}o("GA_googleAddAttr",re);
function se(a,b){Bc(K(L),a,b)}o("GA_googleAddAdSensePageAttr",se);function te(a,b,c){Cc(K(L),a,b,c)}o("GA_googleAddAdSenseSlotAttr",te);function ue(a,b,c){sd($(),a,b,c)}o("GA_googleCreateDomIframe",ue);function ve(a){$().o(a)}o("GA_googleSetAdContentsBySlot",ve);function we(a){Vd($(),a)}o("GA_googleSetAdContentsBySlotForSync",we);function xe(a){Nd($(),a)}o("GA_googleSetAdContentsBySlotForAsync",xe);function ye(a){$d($(),a)}o("GA_googleSyncAdSlotLoaded",ye);function ze(){Ld($())}
o("GA_googleReallyFetchAds",ze);var Ae=function(){var a=ba.getInstance();ce(a);de(a).tick("jl")};Ae();})()


}
/*
     FILE ARCHIVED ON 02:47:03 Jun 05, 2011 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 00:23:28 Feb 18, 2023.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  exclusion.robots: 0.057
  exclusion.robots.policy: 0.05
  RedisCDXSource: 3.915
  esindex: 0.007
  LoadShardBlock: 95.085 (6)
  PetaboxLoader3.datanode: 96.862 (7)
  CDXLines.iter: 78.803 (3)
  load_resource: 1202.356
  PetaboxLoader3.resolve: 1148.784
*/